version: '3'

services:
  aap:
    image: antonio24073/aapanel:centos-7-preinstalled
    container_name: aapanel
    hostname: aapanel.local
    ports: 
      - 7889:7800
      - 221:21
      - 222:22
      - 443:443
      - 80:80
      - 888:888
    volumes:
      - ./www:/www # run without this, the first time, to copy to your host
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./temp.sh:/temp.sh
    env_file:
      - ./.env