version: '3'

services:
  aap:
    build: ./docker-file
    container_name: aapanel
    hostname: aapanel.local
    ports: 
      - 7889:7800
      - 221:21
      - 222:22
      - 443:443
      - 80:80
      - 888:888
    volumes:
      - ./vol/wwwroot:/www/wwwroot
      - ./vol/data:/www/server/data
      - ./vol/vhost:/www/server/panel/vhost
      - ./vol/server/panel/data:/www/server/panel/data
      - ./vol/wwwlogs:/www/wwwlogs
      - ./vol/backup:/www/backup
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ./.env
    # entrypoint: sh /tail.sh # dev mode
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    ulimits:
      nofile:
        soft: 1024
        hard: 1048576
  wt:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 1800